### ISSUE TITLE
Doc Request: The importance of `Total size`

### ISSUE THREAD

**Issue by alejandro5042** [github/git-sizer#35]
From the [README](https://github.com/github/git-sizer/blob/master/README.md):

> "Total size" is the sum of the sizes of the corresponding objects in their uncompressed form, measured in bytes.

Why is this metric important?

Run on our repo, it gives 41 GB but the packfile is only 5 GB. The 41 GB uncompressed size gives me a 4/10 concern level.

I'd imagine the important stats are the size of the packfile (for cloning), the # of objects (for traversal), and the size of the checkout both in files and size (for normal dev workflows). Those numbers don't currently give me cause for concern in our daily usage.

So why should I be concerned about the _uncompressed_ size of _all_ the blobs in my repo? Wouldn't that include blobs in the history that may not be relevant anymore unless the user asks for them specifically? My best guess is that this metric somehow predicts how `git gc` will perform.

**Comment by mhagger** [comment]
When the uncompressed size is much larger than the on-disk size, that is an indication that things are compressing very well. That's usually because there are large blobs or large trees that are getting modified incrementally many times.

The overall uncompressed size of all objects is a good indication of how expensive commands like `git gc --aggressive` (and `git repack [-f|-F]` and `git pack-objects --no-reuse-delta`), `git fsck`, and `git log [-G|-S]` will be.

The uncompressed size of trees and commits is a good indication of how expensive reachability traversals will be, including clones and fetches and `git gc`. (Bitmaps can help here for some commands.)

**Comment by alejandro5042** [comment]
Thanks for the reply! Makes sense. To close this issue, should we document any of this in the README?
