### ISSUE TITLE
'git sizer --help' doesn't work, but 'git-sizer --help' does

### ISSUE THREAD

**Issue by avar** [github/git-sizer#52]
```
$ git sizer --help
No manual entry for git-sizer
$ git-sizer --help
Usage of :
[...]
```

Maybe just make calling it via `git` an error? See https://public-inbox.org/git/87k1ld1f51.fsf@evledraar.gmail.com/ for details about this anti-pattern.

**Comment by mhagger** [comment]
Another twist: both `git-sizer -h` and `git sizer -h` work!

This is because `git` hijacks the `--help` option if you invoke `git-sizer` via `git`. On the other hand, `git` supports some convenient options that also work for `git-sizer`, like `-c`, `-C`, `--git-dir`, etc. (e.g., `git -C /path/to/repo sizer --verbose` does what you would expect). Therefore I consider the `--help` issue an unfortunate quirk (or even bug) of `git`, but I want to continue allowing it until/unless there is an unambiguous pronouncement from upstream that this usage is deprecated.

Note that the `git-sizer` documentation always shows the program being run as `git-sizer`, for this reason and also because running it as `git sizer` requires `git-sizer` to be in `PATH`. But people who know what they are doing should be free to run it as `git sizer`.

BTW, I think that if we included and installed a `git-sizer` manpage, then `git sizer --help` would start working, at least on systems that support manpages.

**Comment by avar** [comment]
Yes. Having a manpage would make this work. See git-annex for an example,
on git-lfs. Would be a good idea in any case to have one.
