### ISSUE TITLE
Show max push size for any commit

### ISSUE THREAD

**Issue by impredicative** [github/git-sizer#64]
How do I see the max push size for any commit? GitHub apparently restricts this to 2 GB, so it's a useful value to know.

**Comment by mhagger** [comment]
`git-sizer` is currently all about the _logical_ size of the repository, for example the full size of a file _without_ considering that in the Git object database it will probably be stored deltad against other versions of the file and then compressed. GitHub's 2GB limit, on the other hand, is the maximum size of a push _after_ deltaing and compressing the data.

I don't think that it would be possible for `git-sizer` to figure out how much new content was added by each commit relative to its parents in an affordable way.

You could probably rig something together using `git diff-tree` and `git cat-file --batch-check='%(objectsize:disk)'` to give a decent estimate, but that will be a bit expensive if you have to do it for all commits.

But 2GB is quite a big number, isn't it? It's hopefully much bigger than any single commit in your repository. Note also that independent of the limits on the size of a single push, GitHub also strongly suggests that you keep your repository size under 5 GB if at all possible, mostly because that will give you a much snappier experience.

For the initial push of a new repo to GitHub, it seems like trial-and-error doing things like pushing `master~100000`, then `master~75000`, etc. would get you there pretty easily.

I'm closing this issue because I don't think that the proposed feature would fit well in `git-sizer`.
