### ISSUE TITLE
Approximating size shown at https://github.com/settings/repositories

### ISSUE THREAD

**Issue by impredicative** [github/git-sizer#66]
What would be the formula or command for approximating the size of a repo as shown at https://github.com/settings/repositories ? Which numbers do I have to add up? Fwiw, I have the tools `jq` and `bc`.

Alternatively, if `git-sizer` cannot approximate it, how do I do it perhaps using `git` itself?

**Comment by mhagger** [comment]
A good estimate for the repository size shown by GitHub would be to make sure that your repo is garbage-collected and then sum up the size of the packfiles under `.git/objects/pack`. This is an oversimplification and gets more complicated if your repo is a fork of another, and it also depends on how well packed the repository happens to be on our servers, and includes the references that are used to manage pull requests. But it should give you the right ballpark.

This is not something that `git-sizer` can currently approximate because it currently only considers the _logical_ size of the repository, not the size on disk.

**Comment by impredicative** [comment]
Okay, and which of `maxCheckoutBlobSize.value` and `uniqueBlobSize.value` would be a better approximation for it? Or does it depend on other factors? I'm just trying to understand.

**Comment by mhagger** [comment]
> Okay, and which of `maxCheckoutBlobSize.value` and `uniqueBlobSize.value` would be a better approximation for it? Or does it depend on other factors?

In a normal repository, `uniqueBlobSize.value` or possibly the sum `uniqueBlobSize.value + uniqueTreeSize.value + uniqueCommitSize.value + uniqueTagSize.value` would probably be correlated with the repository's on-disk size. But the sum will usually be a lot larger because on disk, Git goes to a lot of work to store things efficiently, for example storing multiple versions of a file as deltas against each other and then compressing the result. How well this deltaing and compression works varies dramatically across repositories.

**Comment by impredicative** [comment]
For convenience, is it possible for git-sizer to add a `totalSize.value` which is this sum?
