### ISSUE TITLE
"git-sizer --version" should show a version number.

### ISSUE THREAD

**Issue by CleanCut** [github/git-sizer#70]
```bash
$ brew info git-sizer
git-sizer: stable 1.3.0 (bottled)
[snip]

$ git-sizer --version
git-sizer build
```

**Comment by mhagger** [comment]
The released versions of `git-sizer` have the correct built-in version number. This is arranged by setting a `VERSION` parameter on the `Makefile`.

If you are building a release with the `Makefile`, it insists that a version number be specified. And any build sets a "build version" based on the output of `git describe` and uses that if the version wasn't specified. If that fails, it sets the build version to "unknown".

But, you seem to be running a version that you installed using homebrew. [That formula](https://github.com/Homebrew/homebrew-core/blob/326e8fe11dab2889b0fb49bd4e18dfe26fb4113d/Formula/git-sizer.rb):

* Doesn't use `make`, so the build version isn't set
* Doesn't have a backing Git repository at all, so `git describe` wouldn't work even if it _were_ being attempted
* Doesn't build a release in the sense of the `Makefile`, so there is nothing insisting that a `VERSION` be set.

Instead, it is apparently using a tarball file downloaded using a tarball obtained from a URL like `https://github.com/github/git-sizer/archive/v1.3.0.tar.gz` and then building directly with `go`. GitHub creates these tarballs using the equivalent of `git archive`, so it doesn't contain any version information.

I can think of three possible approaches to fix this problem:

1. Somehow store version information in the repository commits that correspond to release tags, for example by adding a file with contents like

        package main

        func init() {
            ReleaseVersion = "1.2.3"
        }
    The awkward thing about this approach is that we would only want that file in release versions, not in other commits, so we'd either need to do this on a branch or we'd need to follow it immediately with another commit that clears the version information.

2. Change the homebrew formula to specify the version when compiling, ultimately with something like

        go build -ldflags "-X main.ReleaseVersion=1.2.3" […]

    This would put the burden on them to keep the version number in sync with the version downloaded, but maybe that's not too bad given that they could couple the version number set here with the version number that is embedded in the tarball URL.

3. Produce a proper source tarball as part of the release process, bake the release number into that file, and change the homebrew formula to build from that rather than from the GitHub-generated tarball.

**Comment by CleanCut** [comment]
> 2\. Change the homebrew formula to specify the version when compiling, ultimately with something like
>     ```
>      go build -ldflags "-X main.ReleaseVersion=1.2.3" […]
>     ```

I looked into this option. Homebrew correctly detects the version and sets a `version` variable that can be used, so that part isn't a problem. Something is weird with paths, though. When I try this modification to the brewfile locally:

```diff
--- a/Formula/git-sizer.rb
+++ b/Formula/git-sizer.rb
@@ -20,7 +20,7 @@ class GitSizer < Formula
     ENV["GO111MODULE"] = "auto"
     (buildpath/"src/github.com/github/git-sizer").install buildpath.children
     cd "src/github.com/github/git-sizer" do
-      system "go", "build", "-o", bin/"git-sizer"
+      system "go", "build", "-o", bin/"git-sizer", "-ldflags", "-X", "main.ReleaseVersion=#{version}"
       prefix.install_metafiles
     end
   end
```

I get this error:

```
$ brew reinstall --build-from-source git-sizer
==> Downloading https://github.com/github/git-sizer/archive/v1.3.0.tar.gz
Already downloaded: /Users/cleancut/Library/Caches/Homebrew/downloads/2bb6fde4cccc8a12547a2f9e0854b34a642d54981dd3e7cf8e5fb63937298257--git-sizer-1.3.0.tar.gz
==> Reinstalling git-sizer
==> go build -o /usr/local/Cellar/git-sizer/1.3.0/bin/git-sizer -ldflags -X main.ReleaseVersion=1.3.0
Last 15 lines from /Users/cleancut/Library/Logs/Homebrew/git-sizer/01.go:
2021-04-19 13:31:58 -0600

go
build
-o
/usr/local/Cellar/git-sizer/1.3.0/bin/git-sizer
-ldflags
-X
main.ReleaseVersion=1.3.0

cannot find package "main.ReleaseVersion=1.3.0" in any of:
        /usr/local/Cellar/go/1.16.3/libexec/src/main.ReleaseVersion=1.3.0 (from $GOROOT)
        /private/tmp/git-sizer-20210419-14276-m19ezz/git-sizer-1.3.0/src/main.ReleaseVersion=1.3.0 (from $GOPATH)
```

Obviously the version is set correctly.  I tried to peek in `/private/tmp/git-sizer-20210419-14276-m19ezz/git-sizer-1.3.0/` but it was cleaned up.  Is this some go path trickiness?  My version of go is:

```shell
$ go version
go version go1.16.3 darwin/amd64
```

Here is the content of the referenced log file, but the extra info is mostly just environment variables: [01.go.zip](https://github.com/github/git-sizer/files/6338592/01.go.zip)

**Comment by mhagger** [comment]
@cleancut: thanks for looking into this!

I think that the `-X` and the `main.ReleaseVersion=1.3.0` would have to be in a single argument, to get `-ldflags` to pass both of them to the linker:

    system "go", "build", "-o", bin/"git-sizer", "-ldflags", "-X main.ReleaseVersion=#{version}"

**Comment by CleanCut** [comment]
Aha! That makes perfect sense. I should have noticed that when I read the docs for `-ldflags`.  With that change, it works perfectly:

```
$ brew reinstall --build-from-source git-sizer
==> Downloading https://github.com/github/git-sizer/archive/v1.3.0.tar.gz
Already downloaded: /Users/cleancut/Library/Caches/Homebrew/downloads/2bb6fde4cccc8a12547a2f9e0854b34a642d54981dd3e7cf8e5fb63937298257--git-sizer-1.3.0.tar.gz
==> Reinstalling git-sizer
==> go build -o /usr/local/Cellar/git-sizer/1.3.0/bin/git-sizer -ldflags -X main.ReleaseVersion=1.3.0
🍺  /usr/local/Cellar/git-sizer/1.3.0: 5 files, 3.3MB, built in 7 seconds

$ git-sizer --version
git-sizer release 1.3.0
```

I submitted a PR to homebrew to fix the issue. As there is nothing left to discuss, I'll go ahead and close this issue. Thanks! ❤️

**Comment by mhagger** [comment]
Thanks, @CleanCut! :sparkles:
